baseURL = 'https://pragmata.studio'
defaultContentLanguage = 'en'
enableRobotsTXT = true

[params]
email = 'info@pragmata.studio'
phone = '+1 (505) 234-5392'
linkedIn = 'https://www.linkedin.com/company/pragmatastudio'
twitter = 'pragmatastudio'
ein = '365122076'
foundingDate = '2024-10-01'

[languages]
[languages.en]
languageName = 'English'
languageCode = 'en'
weight = 1

[outputs]
home = ['html', 'rss']
page = ['html', 'rss']
section = ['html', 'rss']
taxonomy = []
